#!/usr/bin/env python

import numpy as np
import math
import sys
import rospy
import cv2
import PyKDL

import tiago_kb.places_xml as px

def main():
    # Output path for tests
    output_path = '/home/dseredyn/tiago_public_ws'
    rospy.init_node('knowledge_base')
    rospy.sleep(0.5)

    places_xml = rospy.get_param('~places_xml')

    #px.test_EmbeddedImage(output_path)
    #px.test_PlacesXML(output_path, places_xml)

    print 'Parsing file "' + places_xml + '"'
    places = px.PlacesXml(places_xml)

if __name__ == '__main__':
    main()
