#!/usr/bin/env python

import rospy
import os
import tiago_kb.places_xml as px

def main():
    # Output path for tests
    output_path = '/tmp/tiago_kb'
    try:
        os.mkdir(output_path)
    except Exception as e:
        print e

    rospy.init_node('knowledge_base')
    rospy.sleep(0.5)

    places_xml = rospy.get_param('~places_xml')

    px.test_EmbeddedImage(output_path)
    px.test_PlacesXML(output_path, places_xml)

    # Read database with places
    #print 'Parsing file "' + places_xml + '"'
    #places = px.PlacesXml(places_xml)

if __name__ == '__main__':
    main()
