#!/usr/bin/env python
import rospy
import smach
import smach_ros

from tiago_behaviours_msgs.msg import BringGoodsAction
import tiago_smach.bring_goods

def main():
    rospy.init_node('bring_goods_server')
    rospy.sleep(1.0)

    # Construct state machine
    sm = tiago_smach.bring_goods.BringGoods()

    # # Smach viewer
    sis = smach_ros.IntrospectionServer('bring_goods_server', sm, '/SM_BRING_GOODS_SERVER')
    sis.start()

    # Construct action server wrapper
    asw = smach_ros.ActionServerWrapper(
        server_name='bring_goods',
        action_spec=BringGoodsAction,
        wrapped_container=sm,
        succeeded_outcomes=['FINISHED'],
        aborted_outcomes=['FAILED'],
        preempted_outcomes=['PREEMPTED'],
        goal_key='goods_name')
        # feedback_key='sm_feedback',
        # result_key='sm_result')

    # Run the server in a background thread
    asw.run_server()
    rospy.spin()
    sis.stop()

if __name__ == '__main__':
    main()
